{application,twitter_streams,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib,oauth]},
              {mod,{twitter_streams_app,[]}},
              {env,[]},
              {modules,[twitter_streams_app,twitter_streams_client,
                        twitter_streams_sup]}]}.
